### PR TITLE
Fixed a few language errors in comments and an old Python 2 legacy feature that had no use.

### PR DESCRIPTION
**Pull request by bernd-wechner**
As requested. Hope it's good. Included a few typo fixes.

### CODE REVIEW

**Comment by bernd-wechner** [comment]
Not sure what the Travis failures are about. But curious.

**Comment by sublee** [comment]
Thank you for the good PR.  Can you separate this PR to for comments and for `long`?  I think they are not an atomic patch.

`trueskill` is intended to support both Python 2 and 3.  So the `__long__` magic method should not be removed.  It would be great if you implement it with `past.builtins.long` to support both: http://python-future.org/compatible_idioms.html#long-integers

**Review by sublee — APPROVED** [review]
Thank you!

**Review by sublee — APPROVED** [review]
Typos should be fixed. I'll merge it and recover `__long__` later.

**Comment by bernd-wechner** [comment]
Sorry I dropped the ball on this. Thanks for finishing it up!

**Comment by sublee** [comment]
Sorry for my TOO late response. 🙏

**Pull request merged**
